# Generated by Django 5.0 on 2023-12-17 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Write shows name')),
                ('image', models.ImageField(upload_to='shows/', verbose_name='Add photos')),
                ('description', models.TextField(blank=True, verbose_name='Give shows description')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(5000)], verbose_name='Write the price')),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Kids', 'Kids'), ('Adult', 'Adult')], max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('trailer', models.URLField(verbose_name='Write the link to trailer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
