# Generated by Django 3.2.5 on 2024-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'М'), ('FEMALE', 'Ж')], max_length=100, null=True, verbose_name='Ваш пол'),
        ),
    ]
